DROP TABLE MEDICO_RESPONSAVEL_LAUDO;

DROP TABLE EXAME_RADIOLOGICO;

DROP TABLE MEDICO_CLASSIFICACAO;

DROP TABLE EQUIPAMENTO_RADIOLOGICO;

DROP TABLE CLINICA;

DROP TABLE CLASSIFICACAO_MEDICO;

DROP TABLE EXAME;

DROP TABLE PACIENTE;

DROP TABLE MEDICO;

DROP TABLE REGIAO_EXAME;

