CREATE TABLE REGIAO_EXAME (
  COD_REGIAO INTEGER NOT NULL AUTO_INCREMENT,
  NOM_REGIAO VARCHAR(50) NULL,
  PRIMARY KEY(COD_REGIAO)
);

CREATE TABLE MEDICO (
  COD_MEDICO INTEGER NOT NULL AUTO_INCREMENT,
  NOM_MEDICO VARCHAR(50) NULL,
  SBN_MEDICO VARCHAR(30) NULL,
  NUM_CRM INTEGER NULL,
  NUM_USER_BANCO INTEGER NULL,
  PRIMARY KEY(COD_MEDICO)
);

CREATE TABLE PACIENTE (
  COD_PACIENTE VARCHAR(8) NOT NULL,
  NOM_PACIENTE VARCHAR(60) NULL,
  SBN_PACIENTE VARCHAR(30) NULL,
  IDF_COR INTEGER NULL,
  IDF_SEXO VARCHAR(1) NULL,
  DTA_NASCIMENTO DATE NULL,
  PRIMARY KEY(COD_PACIENTE)
);

CREATE TABLE EXAME (
  COD_EXAME INTEGER NOT NULL AUTO_INCREMENT,
  NOM_EXAME VARCHAR(50) NULL,
  PRIMARY KEY(COD_EXAME)
);

CREATE TABLE CLASSIFICACAO_MEDICO (
  COD_CLASSIFICACAO INTEGER NOT NULL AUTO_INCREMENT,
  NOM_CLASSIFICACAO VARCHAR(30) NULL,
  PRIMARY KEY(COD_CLASSIFICACAO)
);

CREATE TABLE CLINICA (
  COD_CLINICA INTEGER NOT NULL AUTO_INCREMENT,
  NOM_CLINICA VARCHAR(50) NULL,
  COD_CLINICA_PRODESP VARCHAR(4) NULL,
  PRIMARY KEY(COD_CLINICA)
);

CREATE TABLE EQUIPAMENTO_RADIOLOGICO (
  COD_EQUIPAMENTO INTEGER NOT NULL AUTO_INCREMENT,
  NOM_EQUIPAMENTO VARCHAR(40) NULL,
  NUM_SALA VARCHAR(5) NULL,
  NUM_CORREDOR VARCHAR(5) NULL,
  DSC_MARCA VARCHAR(40) NULL,
  COD_EQUIPAMENTO_PRODESP VARCHAR(4) NULL,
  PRIMARY KEY(COD_EQUIPAMENTO)
);

CREATE TABLE MEDICO_CLASSIFICACAO (
  COD_MEDICO INTEGER NOT NULL AUTO_INCREMENT,
  COD_CLASSIFICACAO INTEGER NOT NULL,
  CLASSIFICACAO_MEDICO_COD_CLASSIFICACAO INTEGER NULL,
  MEDICO_COD_MEDICO INTEGER NULL,
  IDF_ATIVO VARCHAR(1) NULL,
  PRIMARY KEY(COD_MEDICO, COD_CLASSIFICACAO),
  INDEX MEDICO_CLASSIFICACAO_FKIndex1(MEDICO_COD_MEDICO),
  INDEX MEDICO_CLASSIFICACAO_FKIndex2(CLASSIFICACAO_MEDICO_COD_CLASSIFICACAO),
  FOREIGN KEY(MEDICO_COD_MEDICO)
    REFERENCES MEDICO(COD_MEDICO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CLASSIFICACAO_MEDICO_COD_CLASSIFICACAO)
    REFERENCES CLASSIFICACAO_MEDICO(COD_CLASSIFICACAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE EXAME_RADIOLOGICO (
  NUM_EXAME INTEGER NOT NULL AUTO_INCREMENT,
  DIG_EXAME INTEGER NOT NULL,
  PACIENTE_COD_PACIENTE VARCHAR(8) NOT NULL,
  REGIAO_EXAME_COD_REGIAO INTEGER NULL,
  CLINICA_COD_CLINICA INTEGER NULL,
  EQUIPAMENTO_RADIOLOGICO_COD_EQUIPAMENTO INTEGER NULL,
  EXAME_COD_EXAME INTEGER NULL,
  COD_PACIENTE CHAR(8) NULL,
  COD_EXAME INTEGER NULL,
  COD_REGIAO INTEGER NULL,
  COD_EQUIPAMENTO INTEGER NULL,
  DTA_REALIZACAO_EXAME DATE NULL,
  DSC_SUSPEITA VARCHAR(20) NULL,
  IDF_TIPO_LAUDO CHAR(1) NULL,
  DTA_DIGITACAO_LAUDO_PROVISORIO DATE NULL,
  DTA_APR_LAUDO_DEFINITIVO DATE NULL,
  DSC_CONCLUSAO VARCHAR(255) NULL,
  DSC_DESCRICAO LONGTEXT NULL,
  NUM_USER_REGISTRO_EXAME INTEGER NULL,
  PRIMARY KEY(NUM_EXAME, DIG_EXAME),
  INDEX EXAME_RADIOLOGICO_FKIndex1(PACIENTE_COD_PACIENTE),
  INDEX EXAME_RADIOLOGICO_FKIndex2(EQUIPAMENTO_RADIOLOGICO_COD_EQUIPAMENTO),
  INDEX EXAME_RADIOLOGICO_FKIndex3(EXAME_COD_EXAME),
  INDEX EXAME_RADIOLOGICO_FKIndex4(CLINICA_COD_CLINICA),
  INDEX EXAME_RADIOLOGICO_FKIndex5(REGIAO_EXAME_COD_REGIAO),
  FOREIGN KEY(PACIENTE_COD_PACIENTE)
    REFERENCES PACIENTE(COD_PACIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(EQUIPAMENTO_RADIOLOGICO_COD_EQUIPAMENTO)
    REFERENCES EQUIPAMENTO_RADIOLOGICO(COD_EQUIPAMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(EXAME_COD_EXAME)
    REFERENCES EXAME(COD_EXAME)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CLINICA_COD_CLINICA)
    REFERENCES CLINICA(COD_CLINICA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(REGIAO_EXAME_COD_REGIAO)
    REFERENCES REGIAO_EXAME(COD_REGIAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE MEDICO_RESPONSAVEL_LAUDO (
  NUM_EXAME INTEGER NOT NULL AUTO_INCREMENT,
  DIG_EXAME INTEGER NOT NULL,
  COD_MEDICO INTEGER NOT NULL,
  COD_CLASSIFICACAO INTEGER NOT NULL,
  MEDICO_CLASSIFICACAO_COD_CLASSIFICACAO INTEGER NOT NULL,
  MEDICO_CLASSIFICACAO_COD_MEDICO INTEGER NOT NULL,
  EXAME_RADIOLOGICO_DIG_EXAME INTEGER NULL,
  EXAME_RADIOLOGICO_NUM_EXAME INTEGER NULL,
  PRIMARY KEY(NUM_EXAME, DIG_EXAME, COD_MEDICO, COD_CLASSIFICACAO),
  INDEX MEDICO_RESPONSAVEL_LAUDO_FKIndex1(MEDICO_CLASSIFICACAO_COD_MEDICO, MEDICO_CLASSIFICACAO_COD_CLASSIFICACAO),
  INDEX MEDICO_RESPONSAVEL_LAUDO_FKIndex2(EXAME_RADIOLOGICO_NUM_EXAME, EXAME_RADIOLOGICO_DIG_EXAME),
  FOREIGN KEY(MEDICO_CLASSIFICACAO_COD_MEDICO, MEDICO_CLASSIFICACAO_COD_CLASSIFICACAO)
    REFERENCES MEDICO_CLASSIFICACAO(COD_MEDICO, COD_CLASSIFICACAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(EXAME_RADIOLOGICO_NUM_EXAME, EXAME_RADIOLOGICO_DIG_EXAME)
    REFERENCES EXAME_RADIOLOGICO(NUM_EXAME, DIG_EXAME)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

