package br.edu.unifei.beans;

// Generated 30/10/2008 01:01:30 by Hibernate Tools 3.2.2.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ClassificacaoMedico generated by hbm2java
 */
public class ClassificacaoMedico implements java.io.Serializable {

	private Integer codClassificacao;
	private String nomClassificacao;
	private Set<MedicoClassificacao> medicoClassificacaos = new HashSet<MedicoClassificacao>(
			0);

	public ClassificacaoMedico() {
	}

	public ClassificacaoMedico(String nomClassificacao,
			Set<MedicoClassificacao> medicoClassificacaos) {
		this.nomClassificacao = nomClassificacao;
		this.medicoClassificacaos = medicoClassificacaos;
	}

	public Integer getCodClassificacao() {
		return this.codClassificacao;
	}

	public void setCodClassificacao(Integer codClassificacao) {
		this.codClassificacao = codClassificacao;
	}

	public String getNomClassificacao() {
		return this.nomClassificacao;
	}

	public void setNomClassificacao(String nomClassificacao) {
		this.nomClassificacao = nomClassificacao;
	}

	public Set<MedicoClassificacao> getMedicoClassificacaos() {
		return this.medicoClassificacaos;
	}

	public void setMedicoClassificacaos(
			Set<MedicoClassificacao> medicoClassificacaos) {
		this.medicoClassificacaos = medicoClassificacaos;
	}

}
