package br.edu.unifei.beans;

// Generated 30/10/2008 01:01:30 by Hibernate Tools 3.2.2.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EquipamentoRadiologico generated by hbm2java
 */
public class EquipamentoRadiologico implements java.io.Serializable {

	private Integer codEquipamento;
	private String nomEquipamento;
	private String numSala;
	private String numCorredor;
	private String dscMarca;
	private String codEquipamentoProdesp;
	private Set<ExameRadiologico> exameRadiologicos = new HashSet<ExameRadiologico>(
			0);

	public EquipamentoRadiologico() {
	}

	public EquipamentoRadiologico(String nomEquipamento, String numSala,
			String numCorredor, String dscMarca, String codEquipamentoProdesp,
			Set<ExameRadiologico> exameRadiologicos) {
		this.nomEquipamento = nomEquipamento;
		this.numSala = numSala;
		this.numCorredor = numCorredor;
		this.dscMarca = dscMarca;
		this.codEquipamentoProdesp = codEquipamentoProdesp;
		this.exameRadiologicos = exameRadiologicos;
	}

	public Integer getCodEquipamento() {
		return this.codEquipamento;
	}

	public void setCodEquipamento(Integer codEquipamento) {
		this.codEquipamento = codEquipamento;
	}

	public String getNomEquipamento() {
		return this.nomEquipamento;
	}

	public void setNomEquipamento(String nomEquipamento) {
		this.nomEquipamento = nomEquipamento;
	}

	public String getNumSala() {
		return this.numSala;
	}

	public void setNumSala(String numSala) {
		this.numSala = numSala;
	}

	public String getNumCorredor() {
		return this.numCorredor;
	}

	public void setNumCorredor(String numCorredor) {
		this.numCorredor = numCorredor;
	}

	public String getDscMarca() {
		return this.dscMarca;
	}

	public void setDscMarca(String dscMarca) {
		this.dscMarca = dscMarca;
	}

	public String getCodEquipamentoProdesp() {
		return this.codEquipamentoProdesp;
	}

	public void setCodEquipamentoProdesp(String codEquipamentoProdesp) {
		this.codEquipamentoProdesp = codEquipamentoProdesp;
	}

	public Set<ExameRadiologico> getExameRadiologicos() {
		return this.exameRadiologicos;
	}

	public void setExameRadiologicos(Set<ExameRadiologico> exameRadiologicos) {
		this.exameRadiologicos = exameRadiologicos;
	}

}
