package br.edu.unifei.beans;

// Generated 30/10/2008 01:01:30 by Hibernate Tools 3.2.2.CR1

/**
 * ExameRadiologicoId generated by hbm2java
 */
public class ExameRadiologicoId implements java.io.Serializable {

	private int numExame;
	private int digExame;

	public ExameRadiologicoId() {
	}

	public ExameRadiologicoId(int numExame, int digExame) {
		this.numExame = numExame;
		this.digExame = digExame;
	}

	public int getNumExame() {
		return this.numExame;
	}

	public void setNumExame(int numExame) {
		this.numExame = numExame;
	}

	public int getDigExame() {
		return this.digExame;
	}

	public void setDigExame(int digExame) {
		this.digExame = digExame;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExameRadiologicoId))
			return false;
		ExameRadiologicoId castOther = (ExameRadiologicoId) other;

		return (this.getNumExame() == castOther.getNumExame())
				&& (this.getDigExame() == castOther.getDigExame());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumExame();
		result = 37 * result + this.getDigExame();
		return result;
	}

}
