package br.edu.unifei.beans;

// Generated 30/10/2008 01:01:30 by Hibernate Tools 3.2.2.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ExameRadiologico generated by hbm2java
 */
public class ExameRadiologico implements java.io.Serializable {

	private ExameRadiologicoId id;
	private RegiaoExame regiaoExame;
	private EquipamentoRadiologico equipamentoRadiologico;
	private Paciente paciente;
	private Exame exame;
	private Clinica clinica;
	private String codPaciente;
	private Integer codExame;
	private Integer codRegiao;
	private Integer codEquipamento;
	private Date dtaRealizacaoExame;
	private String dscSuspeita;
	private Character idfTipoLaudo;
	private Date dtaDigitacaoLaudoProvisorio;
	private Date dtaAprLaudoDefinitivo;
	private String dscConclusao;
	private String dscDescricao;
	private Integer numUserRegistroExame;
	private Set<MedicoResponsavelLaudo> medicoResponsavelLaudos = new HashSet<MedicoResponsavelLaudo>(
			0);

	public ExameRadiologico() {
	}

	public ExameRadiologico(ExameRadiologicoId id, Paciente paciente) {
		this.id = id;
		this.paciente = paciente;
	}

	public ExameRadiologico(ExameRadiologicoId id, RegiaoExame regiaoExame,
			EquipamentoRadiologico equipamentoRadiologico, Paciente paciente,
			Exame exame, Clinica clinica, String codPaciente, Integer codExame,
			Integer codRegiao, Integer codEquipamento, Date dtaRealizacaoExame,
			String dscSuspeita, Character idfTipoLaudo,
			Date dtaDigitacaoLaudoProvisorio, Date dtaAprLaudoDefinitivo,
			String dscConclusao, String dscDescricao,
			Integer numUserRegistroExame,
			Set<MedicoResponsavelLaudo> medicoResponsavelLaudos) {
		this.id = id;
		this.regiaoExame = regiaoExame;
		this.equipamentoRadiologico = equipamentoRadiologico;
		this.paciente = paciente;
		this.exame = exame;
		this.clinica = clinica;
		this.codPaciente = codPaciente;
		this.codExame = codExame;
		this.codRegiao = codRegiao;
		this.codEquipamento = codEquipamento;
		this.dtaRealizacaoExame = dtaRealizacaoExame;
		this.dscSuspeita = dscSuspeita;
		this.idfTipoLaudo = idfTipoLaudo;
		this.dtaDigitacaoLaudoProvisorio = dtaDigitacaoLaudoProvisorio;
		this.dtaAprLaudoDefinitivo = dtaAprLaudoDefinitivo;
		this.dscConclusao = dscConclusao;
		this.dscDescricao = dscDescricao;
		this.numUserRegistroExame = numUserRegistroExame;
		this.medicoResponsavelLaudos = medicoResponsavelLaudos;
	}

	public ExameRadiologicoId getId() {
		return this.id;
	}

	public void setId(ExameRadiologicoId id) {
		this.id = id;
	}

	public RegiaoExame getRegiaoExame() {
		return this.regiaoExame;
	}

	public void setRegiaoExame(RegiaoExame regiaoExame) {
		this.regiaoExame = regiaoExame;
	}

	public EquipamentoRadiologico getEquipamentoRadiologico() {
		return this.equipamentoRadiologico;
	}

	public void setEquipamentoRadiologico(
			EquipamentoRadiologico equipamentoRadiologico) {
		this.equipamentoRadiologico = equipamentoRadiologico;
	}

	public Paciente getPaciente() {
		return this.paciente;
	}

	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	public Exame getExame() {
		return this.exame;
	}

	public void setExame(Exame exame) {
		this.exame = exame;
	}

	public Clinica getClinica() {
		return this.clinica;
	}

	public void setClinica(Clinica clinica) {
		this.clinica = clinica;
	}

	public String getCodPaciente() {
		return this.codPaciente;
	}

	public void setCodPaciente(String codPaciente) {
		this.codPaciente = codPaciente;
	}

	public Integer getCodExame() {
		return this.codExame;
	}

	public void setCodExame(Integer codExame) {
		this.codExame = codExame;
	}

	public Integer getCodRegiao() {
		return this.codRegiao;
	}

	public void setCodRegiao(Integer codRegiao) {
		this.codRegiao = codRegiao;
	}

	public Integer getCodEquipamento() {
		return this.codEquipamento;
	}

	public void setCodEquipamento(Integer codEquipamento) {
		this.codEquipamento = codEquipamento;
	}

	public Date getDtaRealizacaoExame() {
		return this.dtaRealizacaoExame;
	}

	public void setDtaRealizacaoExame(Date dtaRealizacaoExame) {
		this.dtaRealizacaoExame = dtaRealizacaoExame;
	}

	public String getDscSuspeita() {
		return this.dscSuspeita;
	}

	public void setDscSuspeita(String dscSuspeita) {
		this.dscSuspeita = dscSuspeita;
	}

	public Character getIdfTipoLaudo() {
		return this.idfTipoLaudo;
	}

	public void setIdfTipoLaudo(Character idfTipoLaudo) {
		this.idfTipoLaudo = idfTipoLaudo;
	}

	public Date getDtaDigitacaoLaudoProvisorio() {
		return this.dtaDigitacaoLaudoProvisorio;
	}

	public void setDtaDigitacaoLaudoProvisorio(Date dtaDigitacaoLaudoProvisorio) {
		this.dtaDigitacaoLaudoProvisorio = dtaDigitacaoLaudoProvisorio;
	}

	public Date getDtaAprLaudoDefinitivo() {
		return this.dtaAprLaudoDefinitivo;
	}

	public void setDtaAprLaudoDefinitivo(Date dtaAprLaudoDefinitivo) {
		this.dtaAprLaudoDefinitivo = dtaAprLaudoDefinitivo;
	}

	public String getDscConclusao() {
		return this.dscConclusao;
	}

	public void setDscConclusao(String dscConclusao) {
		this.dscConclusao = dscConclusao;
	}

	public String getDscDescricao() {
		return this.dscDescricao;
	}

	public void setDscDescricao(String dscDescricao) {
		this.dscDescricao = dscDescricao;
	}

	public Integer getNumUserRegistroExame() {
		return this.numUserRegistroExame;
	}

	public void setNumUserRegistroExame(Integer numUserRegistroExame) {
		this.numUserRegistroExame = numUserRegistroExame;
	}

	public Set<MedicoResponsavelLaudo> getMedicoResponsavelLaudos() {
		return this.medicoResponsavelLaudos;
	}

	public void setMedicoResponsavelLaudos(
			Set<MedicoResponsavelLaudo> medicoResponsavelLaudos) {
		this.medicoResponsavelLaudos = medicoResponsavelLaudos;
	}

}
