package br.edu.unifei.beans;

// Generated 30/10/2008 01:01:30 by Hibernate Tools 3.2.2.CR1

/**
 * MedicoResponsavelLaudo generated by hbm2java
 */
public class MedicoResponsavelLaudo implements java.io.Serializable {

	private MedicoResponsavelLaudoId id;
	private MedicoClassificacao medicoClassificacao;
	private ExameRadiologico exameRadiologico;

	public MedicoResponsavelLaudo() {
	}

	public MedicoResponsavelLaudo(MedicoResponsavelLaudoId id,
			MedicoClassificacao medicoClassificacao) {
		this.id = id;
		this.medicoClassificacao = medicoClassificacao;
	}

	public MedicoResponsavelLaudo(MedicoResponsavelLaudoId id,
			MedicoClassificacao medicoClassificacao,
			ExameRadiologico exameRadiologico) {
		this.id = id;
		this.medicoClassificacao = medicoClassificacao;
		this.exameRadiologico = exameRadiologico;
	}

	public MedicoResponsavelLaudoId getId() {
		return this.id;
	}

	public void setId(MedicoResponsavelLaudoId id) {
		this.id = id;
	}

	public MedicoClassificacao getMedicoClassificacao() {
		return this.medicoClassificacao;
	}

	public void setMedicoClassificacao(MedicoClassificacao medicoClassificacao) {
		this.medicoClassificacao = medicoClassificacao;
	}

	public ExameRadiologico getExameRadiologico() {
		return this.exameRadiologico;
	}

	public void setExameRadiologico(ExameRadiologico exameRadiologico) {
		this.exameRadiologico = exameRadiologico;
	}

}
