package br.edu.unifei.beans;

// Generated 30/10/2008 01:01:30 by Hibernate Tools 3.2.2.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico implements java.io.Serializable {

	private Integer codMedico;
	private String nomMedico;
	private String sbnMedico;
	private Integer numCrm;
	private Integer numUserBanco;
	private Set<MedicoClassificacao> medicoClassificacaos = new HashSet<MedicoClassificacao>(
			0);

	public Medico() {
	}

	public Medico(String nomMedico, String sbnMedico, Integer numCrm,
			Integer numUserBanco, Set<MedicoClassificacao> medicoClassificacaos) {
		this.nomMedico = nomMedico;
		this.sbnMedico = sbnMedico;
		this.numCrm = numCrm;
		this.numUserBanco = numUserBanco;
		this.medicoClassificacaos = medicoClassificacaos;
	}

	public Integer getCodMedico() {
		return this.codMedico;
	}

	public void setCodMedico(Integer codMedico) {
		this.codMedico = codMedico;
	}

	public String getNomMedico() {
		return this.nomMedico;
	}

	public void setNomMedico(String nomMedico) {
		this.nomMedico = nomMedico;
	}

	public String getSbnMedico() {
		return this.sbnMedico;
	}

	public void setSbnMedico(String sbnMedico) {
		this.sbnMedico = sbnMedico;
	}

	public Integer getNumCrm() {
		return this.numCrm;
	}

	public void setNumCrm(Integer numCrm) {
		this.numCrm = numCrm;
	}

	public Integer getNumUserBanco() {
		return this.numUserBanco;
	}

	public void setNumUserBanco(Integer numUserBanco) {
		this.numUserBanco = numUserBanco;
	}

	public Set<MedicoClassificacao> getMedicoClassificacaos() {
		return this.medicoClassificacaos;
	}

	public void setMedicoClassificacaos(
			Set<MedicoClassificacao> medicoClassificacaos) {
		this.medicoClassificacaos = medicoClassificacaos;
	}

}
