package br.edu.unifei.beans;

// Generated 30/10/2008 01:01:30 by Hibernate Tools 3.2.2.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * RegiaoExame generated by hbm2java
 */
public class RegiaoExame implements java.io.Serializable {

	private Integer codRegiao;
	private String nomRegiao;
	private Set<ExameRadiologico> exameRadiologicos = new HashSet<ExameRadiologico>(
			0);

	public RegiaoExame() {
	}

	public RegiaoExame(String nomRegiao, Set<ExameRadiologico> exameRadiologicos) {
		this.nomRegiao = nomRegiao;
		this.exameRadiologicos = exameRadiologicos;
	}

	public Integer getCodRegiao() {
		return this.codRegiao;
	}

	public void setCodRegiao(Integer codRegiao) {
		this.codRegiao = codRegiao;
	}

	public String getNomRegiao() {
		return this.nomRegiao;
	}

	public void setNomRegiao(String nomRegiao) {
		this.nomRegiao = nomRegiao;
	}

	public Set<ExameRadiologico> getExameRadiologicos() {
		return this.exameRadiologicos;
	}

	public void setExameRadiologicos(Set<ExameRadiologico> exameRadiologicos) {
		this.exameRadiologicos = exameRadiologicos;
	}

}
