package br.edu.unifei.beans;

// Generated 30/10/2008 01:01:30 by Hibernate Tools 3.2.2.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MedicoClassificacao generated by hbm2java
 */
public class MedicoClassificacao implements java.io.Serializable {

	private MedicoClassificacaoId id;
	private ClassificacaoMedico classificacaoMedico;
	private Medico medico;
	private String idfAtivo;
	private Set<MedicoResponsavelLaudo> medicoResponsavelLaudos = new HashSet<MedicoResponsavelLaudo>(
			0);

	public MedicoClassificacao() {
	}

	public MedicoClassificacao(MedicoClassificacaoId id) {
		this.id = id;
	}

	public MedicoClassificacao(MedicoClassificacaoId id,
			ClassificacaoMedico classificacaoMedico, Medico medico,
			String idfAtivo, Set<MedicoResponsavelLaudo> medicoResponsavelLaudos) {
		this.id = id;
		this.classificacaoMedico = classificacaoMedico;
		this.medico = medico;
		this.idfAtivo = idfAtivo;
		this.medicoResponsavelLaudos = medicoResponsavelLaudos;
	}

	public MedicoClassificacaoId getId() {
		return this.id;
	}

	public void setId(MedicoClassificacaoId id) {
		this.id = id;
	}

	public ClassificacaoMedico getClassificacaoMedico() {
		return this.classificacaoMedico;
	}

	public void setClassificacaoMedico(ClassificacaoMedico classificacaoMedico) {
		this.classificacaoMedico = classificacaoMedico;
	}

	public Medico getMedico() {
		return this.medico;
	}

	public void setMedico(Medico medico) {
		this.medico = medico;
	}

	public String getIdfAtivo() {
		return this.idfAtivo;
	}

	public void setIdfAtivo(String idfAtivo) {
		this.idfAtivo = idfAtivo;
	}

	public Set<MedicoResponsavelLaudo> getMedicoResponsavelLaudos() {
		return this.medicoResponsavelLaudos;
	}

	public void setMedicoResponsavelLaudos(
			Set<MedicoResponsavelLaudo> medicoResponsavelLaudos) {
		this.medicoResponsavelLaudos = medicoResponsavelLaudos;
	}

}
