package br.edu.unifei.beans;

// Generated 30/10/2008 01:01:30 by Hibernate Tools 3.2.2.CR1

/**
 * MedicoClassificacaoId generated by hbm2java
 */
public class MedicoClassificacaoId implements java.io.Serializable {

	private int codMedico;
	private int codClassificacao;

	public MedicoClassificacaoId() {
	}

	public MedicoClassificacaoId(int codMedico, int codClassificacao) {
		this.codMedico = codMedico;
		this.codClassificacao = codClassificacao;
	}

	public int getCodMedico() {
		return this.codMedico;
	}

	public void setCodMedico(int codMedico) {
		this.codMedico = codMedico;
	}

	public int getCodClassificacao() {
		return this.codClassificacao;
	}

	public void setCodClassificacao(int codClassificacao) {
		this.codClassificacao = codClassificacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MedicoClassificacaoId))
			return false;
		MedicoClassificacaoId castOther = (MedicoClassificacaoId) other;

		return (this.getCodMedico() == castOther.getCodMedico())
				&& (this.getCodClassificacao() == castOther
						.getCodClassificacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodMedico();
		result = 37 * result + this.getCodClassificacao();
		return result;
	}

}
