package br.edu.unifei.beans;

// Generated 30/10/2008 01:01:30 by Hibernate Tools 3.2.2.CR1

/**
 * MedicoResponsavelLaudoId generated by hbm2java
 */
public class MedicoResponsavelLaudoId implements java.io.Serializable {

	private int numExame;
	private int digExame;
	private int codMedico;
	private int codClassificacao;

	public MedicoResponsavelLaudoId() {
	}

	public MedicoResponsavelLaudoId(int numExame, int digExame, int codMedico,
			int codClassificacao) {
		this.numExame = numExame;
		this.digExame = digExame;
		this.codMedico = codMedico;
		this.codClassificacao = codClassificacao;
	}

	public int getNumExame() {
		return this.numExame;
	}

	public void setNumExame(int numExame) {
		this.numExame = numExame;
	}

	public int getDigExame() {
		return this.digExame;
	}

	public void setDigExame(int digExame) {
		this.digExame = digExame;
	}

	public int getCodMedico() {
		return this.codMedico;
	}

	public void setCodMedico(int codMedico) {
		this.codMedico = codMedico;
	}

	public int getCodClassificacao() {
		return this.codClassificacao;
	}

	public void setCodClassificacao(int codClassificacao) {
		this.codClassificacao = codClassificacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MedicoResponsavelLaudoId))
			return false;
		MedicoResponsavelLaudoId castOther = (MedicoResponsavelLaudoId) other;

		return (this.getNumExame() == castOther.getNumExame())
				&& (this.getDigExame() == castOther.getDigExame())
				&& (this.getCodMedico() == castOther.getCodMedico())
				&& (this.getCodClassificacao() == castOther
						.getCodClassificacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumExame();
		result = 37 * result + this.getDigExame();
		result = 37 * result + this.getCodMedico();
		result = 37 * result + this.getCodClassificacao();
		return result;
	}

}
